source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

target 'VisualAnchors_Example', :exclusive => true do
  pod 'VisualAnchors', :path => "../"
end

target 'VisualAnchors_Tests', :exclusive => true do
  pod 'VisualAnchors', :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '~> 3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
