# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild test -workspace Example/VisualAnchors.xcworkspace -scheme VisualAnchors-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
